import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar/Navbar";
import ApolloProviderWrapper from "@/components/ApolloProviderWrapper";

import "@radix-ui/themes/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen flex flex-col">
      <body className={`${inter.className} flex flex-col h-full w-full`}>
        <>
          <Navbar />
          <ApolloProviderWrapper>
            <main className="flex-grow w-full">{children}</main>
          </ApolloProviderWrapper>
          <Footer />
        </>
      </body>
    </html>
  );
}
